title: Dakota Rennels # your name (or website title) here
logo: "profile_pic.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  4+ years of Data Science and Data Analytics 
  experience with extensive experience in 
  advanced data analytics and exploratory 
  data analysis.
  <br><br>
  Currently, I work as a Data Analyst on the
  Data Science team for Oklahoma Office of 
  Management and Enterprise Services. I 
  continuously aiding the State of Oklahoma 
  with data modernization efforts.
  <br><br>
  <a href="https://www.linkedin.com/in/dakota-rennels/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
