title: Dakota Rennels # your name (or website title) here
logo: "images/profile_pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  4+ years of Data Science and Advanced Data Analytics 
  experience with initiatives utilizing advanced data 
  analytics, deploying risk management analysis, and 
  designing data strategy.
  <br><br>
  Currently, I work as a Sr. Data Analyst on 
  the Data Science team for Oklahoma Office of 
  Management and Enterprise Services. Leading
  data modernization efforts through data 
  goverance policy creation and implementation
  while aiding agencies with developing their 
  individual data strategy while aligning with 
  the overall state standard. 
  <br><br>

  <a href="https://www.linkedin.com/in/dakota-rennels/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
