title: Dakota Rennels # your name (or website title) here
logo: "images/profile_pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  6+ years of Data Science and Advanced Data Analytics 
  experience. Specialized in Deep Learning models and AI systems.
  <br><br>
  Currently working as a Data Scientist II on the Data Science team for the State of Oklahoma.
  <br><br>

  <a href="https://www.linkedin.com/in/dakota-rennels/">View My LinkedIn Profile</a> <br>
  <a href="https://unt.joinhandshake.com/stu/users/34620535">View My Handshake Profile</a> <br>
  <a href="https://github.com/dakota-rennels/Python-Notebooks/tree/main">View My Github Repo</a> <br>
  <a href="https://github.com/dakota-rennels/dakota-rennels.github.io/blob/main/Files/Dakota_Rennels_Resume_Data_Science.pdf">View My Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: G-YR9X1RHSJB # your Google Analytics tracking ID here
