title: Dakota Rennels # your name (or website title) here
logo: "images/profile_pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  4+ years of Data Science and Advanced Data Analytics 
  experience.
  <br><br>
  Data Analyst on the Data Science team for Oklahoma 
  Office of Management and Enterprise Services.
  <br><br>

  <a href="https://www.linkedin.com/in/dakota-rennels/">View My LinkedIn Profile</a> <br>
  <a href="https://unt.joinhandshake.com/stu/users/34620535">View My Handshake Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
